name: Run Workflow
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 */1 * *'

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  sync-notion-to-google:
    name: Sync Notion to Google Tasks
    runs-on: self-hosted

    if: github.ref == 'refs/heads/main'  # Only execute on the main branch

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Ensure Python 3.10 in PATH (install if missing)
        shell: bash
        run: |
          if command -v python3.10 &>/dev/null; then
            echo "Python 3.10 is already installed at $(command -v python3.10)."
          else
            echo "Python 3.10 not found. Installing..."
            sudo apt-get update
            sudo apt-get install -y software-properties-common
            sudo add-apt-repository -y ppa:deadsnakes/ppa
            sudo apt-get update
            sudo apt-get install -y python3.10
          fi

          # Ensure Python 3.10 is available in PATH
          if command -v python3.10 &>/dev/null; then
            echo "$(dirname "$(command -v python3.10)")" >> $GITHUB_PATH
          else
            echo "ERROR: Python 3.10 installation failed."
            exit 1
          fi

      - name: Install uv (fast Python installer)
        shell: bash
        run: |
          python3.10 -m pip install --upgrade pip
          python3.10 -m pip install uv

      - name: Install Dependencies with uv
        shell: bash
        run: |
          uv venv .venv --python=python3.10
          uv pip install -r pyproject.toml --extra streamlit_app
        working-directory: ${{ github.workspace }}

      - name: Generate Google API Token
        shell: bash
        run: |
          uv run python3.10 services/google_integration/config_creds.py --save_dir .
        working-directory: ${{ github.workspace }}
        env:
          GOOGLE_ACCESS_TOKEN: ${{ secrets.GOOGLE_ACCESS_TOKEN }}
          GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}

      - name: Sync Notion to Google Tasks
        shell: bash
        run: |
          export TOKEN_PATH="${{ github.workspace }}/token.json"
          uv run python3.10 main.py
        working-directory: ${{ github.workspace }}
        env:
          NOTION_API: ${{ secrets.NOTION_API }}
          DATABASE_ID: ${{ secrets.DATABASE_ID }}
          PROJECT_ROOT: ${{ github.workspace }}

      - name: Retrieve blocked days 
        shell: bash
        run: |
          uv run python3.10 services/dataviz/src/get_blocked_days.py
        working-directory: ${{ github.workspace }}
        env:
          NOTION_API: ${{ secrets.NOTION_API }}
          BLOCKED_DATE_DB_ID: ${{ secrets.BLOCKED_DATE_DB_ID }}
          CALENDAR_URL: ${{ secrets.CALENDAR_URL }}
          PROJECT_ROOT: ${{ github.workspace }}